export const heroPlaceholder = [
  {
    id: 1,
    background: "/assets/hero-section/1.jpg",
    name: "iPhone 15 Pro",
    desc: "Titanium. Begitu kuat. Begitu ringan. Begitu Pro.",
    more: "https://www.apple.com/id/iphone-15-pro/",
    buy: "https://www.apple.com/id/buy/",
  },
  {
    id: 2,
    background: "/assets/hero-section/2.jpg",
    name: "iPhone 15",
    desc: "Kamera baru. Desain baru. Keseruan baru.",
    more: "https://www.apple.com/id/iphone-15/",
    buy: "https://www.apple.com/id/buy/",
  },
  {
    id: 3,
    background: "/assets/hero-section/3.jpg",
    name: "MacBook Air",
    desc: "Laptop M3 tipis. Bertenaga fantastis.",
    more: "https://www.apple.com/id/macbook-air/",
    exp: "Cek kembali untuk informasi ketersediaan",
  },
];

export const productPlaceholder = [
  {
    id: 1,
    icon: "/assets/product-section/icon_1.png",
    background: "/assets/product-section/1.jpg",
    desc: "Lebih pintar. Lebih cerah. Lebih perkasa.",
    more: "https://www.apple.com/id/apple-watch-series-9/",
    buy: "https://www.apple.com/id/buy/",
    color: "black",
  },
  {
    id: 2,
    icon: "/assets/product-section/icon_2.png",
    background: "/assets/product-section/2.jpg",
    desc: "Petualangan level selanjutnya.",
    more: "https://www.apple.com/id/apple-watch-ultra-2/",
    buy: "https://www.apple.com/id/buy/",
    color: "white",
  },
  {
    id: 3,
    name: "iPad",
    background: "/assets/product-section/3.jpg",
    desc: "Disukai semua. Siap berkarya. Luar biasa.",
    more: "https://www.apple.com/id/ipad-10.9/",
    buy: "https://www.apple.com/id/buy/",
    color: "white",
  },
  {
    id: 4,
    name: "iPad Pro",
    background: "/assets/product-section/4.jpg",
    desc: "Bertenaga super berkat M2.",
    more: "https://www.apple.com/id/ipad-pro/",
    buy: "https://www.apple.com/id/buy/",
    color: "black",
  },
  {
    id: 5,
    name: "MacBook Pro",
    background: "/assets/product-section/5.jpg",
    desc: "Begitu mengesankan. Mencuri perhatian.",
    more: "https://www.apple.com/id/macbook-pro/",
    buy: "https://www.apple.com/id/buy/",
    color: "white",
  },
  {
    id: 6,
    name: "AirPods Pro",
    background: "/assets/product-section/6.jpg",
    desc: "Audio Adaptif. Dengarkan sekarang.",
    more: "https://www.apple.com/id/airpods-pro/",
    buy: "https://www.apple.com/id/buy/",
    color: "black",
  },
];

export const images = [
    '/assets/movie-section/1.jpg',
    '/assets/movie-section/2.jpg',
    '/assets/movie-section/3.jpg',
    '/assets/movie-section/4.jpg',
    '/assets/movie-section/5.jpg',
    '/assets/movie-section/6.jpg',
    '/assets/movie-section/7.jpg',
    '/assets/movie-section/8.jpg',
    '/assets/movie-section/9.jpg',
    '/assets/movie-section/10.jpg',
]